version: '2'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 2170066


  fast_api_app:
    build: .
    env_file:
      - config.env
    restart: always
    ports:
      - 8080:80